Repository ozazat/moayo, pull requests merged in 2023-07, with the labels that each got.

#4 feat : Navbar 구현
  package-lock.json
  package.json
  public/iPhone12_Clay_Shadow.png
  src/App.tsx
  src/components/common/MainHeader.tsx
  src/components/common/NavBar.tsx
  src/layout/MainLayout.tsx
  src/layout/SubLayout.tsx
  src/styles/GlobalStyles.styles.ts
Labels: enhancement

#7 design : Navbar 및 iphone 목업 이미지 z-index 수정
  src/App.tsx
  src/components/common/NavBar.tsx
Labels: bug

#23 feat : 일일, 주간, 전체, 검색 거래 내역 컴포넌트 및 신규 내역 추가 버튼 구현
  src/components/ExpenseList.tsx
  src/components/PostBtn.tsx
Labels: enhancement

#28 feat : Add 페이지 레이아웃, 버튼 기능 구현
  src/routes/Add/Add.tsx
Labels: enhancement

#34 feat : daily, add, mainHeader 기능 추가
  src/components/ExpenseList.tsx
  src/components/common/MainHeader.tsx
  src/components/common/NavBar.tsx
  src/components/main/WeeklyList.tsx
  src/routes/Add/Add.tsx
  src/routes/Main/Daily.tsx
  src/store/useTimeStore.ts
Labels: enhancement

#38 Feat/add layout
  src/components/main/MonthStatistics.tsx
  src/routes/Add/Add.tsx
  src/routes/Main/Daily.tsx
Labels: enhancement

#40 design : Main Weekly, Monthly 리스트 컴포넌트 디자인
  src/components/main/MonthlyList.tsx
  src/components/main/WeeklyList.tsx
  src/routes/Main/Monthly.tsx
  src/routes/Main/Weekly.tsx
Labels: enhancement

#42 feat : Weekly!!!!!!1111
  src/components/ExpenseList.tsx
  src/components/main/AllDailyList.tsx
  src/components/main/DailyList.tsx
  src/components/main/WeeklyList.tsx
  src/routes/Main/Daily.tsx
  src/routes/Main/Weekly.tsx
  src/store/useExpensesStore.ts
  src/styles/GlobalStyles.styles.ts
  src/utils/date.ts
Labels: enhancement

#52 docs: 기본 페이지 라우터 변경
  src/App.tsx
Labels: documentation

#58 design : Main 월간 데이터 출력 grid 추가
  index.html
  public/favicon.png
  public/vite.svg
  src/components/main/MonthlyList.tsx
Labels: documentation

#67 design : 일일, 주간, 월간 데이터 CSS 수정
  src/components/ExpenseList.tsx
  src/components/main/DailyList.tsx
  src/components/main/MonthlyList.tsx
  src/components/main/WeeklyList.tsx
Labels: documentation
